#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

INTERNAL_MONITOR="eDP-1"
EXTERNAL_MONITOR="HDMI-1-1"

monitor_add() {
	# Move first 5 desktops to external monitor
	for desktop in $(bspc query -D --names -m "$INTERNAL_MONITOR" | sed 5q); do
		bspc desktop "$desktop" --to-monitor "$EXTERNAL_MONITOR"
	done
}

monitor_remove() {
	echo monitor_remove
	# Add default temp desktop because a minimum of one desktop is required per monitor
	bspc monitor "$EXTERNAL_MONITOR" -a Desktop

	# Move all desktops except the last default desktop to internal monitor
	for desktop in $(bspc query -D -m "$EXTERNAL_MONITOR"); do
		bspc desktop "$desktop" --to-monitor "$INTERNAL_MONITOR"
	done

	# delete default desktops
	bspc desktop Desktop --remove

	# reorder desktops
	bspc monitor "$INTERNAL_MONITOR" -o I II III IV V VI VII VIII IX X
}

if [[ $(bspc query -D -m $INTERNAL_MONITOR | wc -l) -eq 1 ]]; then
	bspc monitor -d I II III IV V VI VII VIII IX X 
fi

bspc config border_width          3
bspc config focused_border_color \#FF453A
bspc config window_gap           12

bspc rule -a Spotify desktop=X
bspc rule -a Brave desktop=I
bspc rule -a Discord desktop=II
bspc rule -a Thunderbird desktop=IV
bspc rule -a Clion desktop=III
bspc rule -a VSCodium desktop=III

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

source $HOME/.fehbg
source $HOME/.config/polybar/launch.sh &
killall dunst && exec /usr/bin/dunst &

if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
	# set xrandr rules for docked setup
	xrandr --output "$INTERNAL_MONITOR" --primary --mode 1920x1080 --pos 0x0 --rotate normal --output "$EXTERNAL_MONITOR" --mode 1920x1080 --pos 1920x0 --rotate normal

	echo "External connected"
	if [[ $(bspc query -D -m $EXTERNAL_MONITOR | wc -l) -lt 5 ]]; then
		echo "External less than 5"
		monitor_add
	fi
else
	# set xrandr rules for mobile setup
	xrandr --output "$INTERNAL_MONITOR" --primary --mode 1920x1080 pos 0x0 --rotate normal --output "$EXTERNAL_MONITOR" --off

	echo "External disconnected"
	if [[ $(bspc query -D -m $INTERNAL_MONITOR |wc -l) -ne 10 ]]; then
		echo "Internal not equal 10"
		monitor_remove
	fi
fi
