theme = "everforest_dark"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.indent-guides]
render = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[editor]
color-modes = true
